# Default values for the Identity Service Helm chart

replicaCount: 1
image:
  repository: ghcr.io/nooshet-backend/identity-service
  tag: development-a8beb29
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: identity.nooshet.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
autossl: {}
# Istio Configuration
istio:
  enabled: true
env:
  application.config.user-service-url: "http://user-service:80"
database:
  host: postgresql-identity
  port: 5432
  name: nooshet_identity
  user: nooshet_identity
  password: identity_password_123
redis:
  host: redis
  port: 6379
