{{- $callers := default (list) .Values.istio.authorization.internalCallers }}
{{- if gt (len $callers) 0 }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: '{{ printf "%s-authz" (include "identity-service.fullname" .) }}'
spec:
  selector:
    matchLabels:
      {{- include "identity-service.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
    - from:
        - source:
            principals: {{ toJson $callers }}
{{- end }}
